### ISSUE TITLE
Meanwhile using with set catalog couldn't start it through other VPN.

### ISSUE THREAD

**Issue by kriszcson** [shiwaforce/poco#75]
A short timeout should be set for the catalog, and if it was not found the script should run over.
It also would be nice if it had a command for updating the catalog, then the autoupdate could be switched off in developer mode.

**Comment by sarkiroka** [comment]
Nice catch! 
I've been frustrated by this for a long time. Actually your second suggestion solves the first problem. That's what developer mode is all about, in this case the developer will control the updating of git repos. So it would be possible to use a different branch from the master in case of a catalog. 
Actually, it is not a necessary condition to have a sub-command to update the catalog. But it would be very convenient for me if there was.

**Comment by gaborkolarovics** [comment]
Nice hit.

Actually, the application handles two types of repositories.
As a project module in the poco.yaml file. And as a catalog in the configuration.

The problem is that always-update can only be turned off for the project module.

I think that for compatibility you should introduce a new configuration called "catalog-update-mode", which can be "always-update" (default) or "manual". And there should be a command to update the catalog manually.

What do you think?

**Comment by sarkiroka** [comment]
I have several comments. I think the forced updating of the catalogue every time is wrong. I think we agree on that. 
Introducing new switches would only complicate a situation that is already difficult. 
I think developer-mode should be the main focus of the catalogue update strategy. If it's "true" then it's the developer's responsibility to keep it fresh when he needs it. From experience, weeks pass between catalog updates, while for projext it's minutes or hours. I think that such a default operation would not cause confusion. 
If developer-mode is set to "false", then the current operation can remain. 

And regardless of these, it should be possible to update the catalogue not with a switch, but defined as a clear new command, if someone still wants to do it manually. For example "poco catalog-update" 

What do you think about such a solution?
